import { Resend } from 'resend';
import { NextResponse } from 'next/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req) {
  try {
    // 1. number ko yahan add kiya
    const { name, email, number, service, message } = await req.json();

    const { data, error } = await resend.emails.send({
      from: 'BizGrow Sales <sales@bizgrow-holdings.net>', 
      to: ['sales@bizgrow-holdings.net'],
      reply_to: email, 
      subject: `New Inquiry: ${service} from ${name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; border: 1px solid #e0e0e0; padding: 30px; border-radius: 12px; color: #333;">
          <h2 style="color: #12066a; margin-top: 0;">New Business Inquiry</h2>
          <p style="font-size: 16px; border-bottom: 1px solid #eee; padding-bottom: 10px;">
            A new lead has been submitted through the <strong>BizGrow Holdings</strong> website.
          </p>
          
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #666; width: 140px;">Client Name:</td>
              <td style="padding: 8px 0;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #666;">Client Email:</td>
              <td style="padding: 8px 0;"><a href="mailto:${email}" style="color: #12066a;">${email}</a></td>
            </tr>
           
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #666;">Phone Number:</td>
              <td style="padding: 8px 0;"><a href="tel:${number}" style="color: #12066a; text-decoration: none;">${number}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 0; font-weight: bold; color: #666;">Service:</td>
              <td style="padding: 8px 0;"><span style="background: #eef2ff; color: #12066a; padding: 4px 10px; border-radius: 5px; font-size: 13px; font-weight: bold;">${service}</span></td>
            </tr>
          </table>

          <div style="background: #fcfcfc; border-left: 4px solid #12066a; padding: 15px; border-radius: 4px; margin-top: 25px;">
            <p style="margin-top: 0; font-weight: bold; color: #12066a;">Message:</p>
            <p style="line-height: 1.6; margin-bottom: 0;">${message}</p>
          </div>

          <p style="margin-top: 30px; font-size: 11px; color: #aaa; text-align: center;">
            This email was automatically generated by the BizGrow Holdings Portal.
          </p>
        </div>
      `,
    });

    if (error) {
      return NextResponse.json({ error }, { status: 400 });
    }

    return NextResponse.json({ success: true, message: "Lead sent successfully", data });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}